# Generated by Django 3.2.5 on 2021-07-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('account', '0002_auto_20210716_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.investor')),
                ('your_requests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.requestsloan')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.offer')),
                ('requests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.requestsloan')),
            ],
        ),
    ]
