# Generated by Django 3.2.5 on 2021-07-16 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20210716_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('loan_period', models.IntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.investor')),
                ('requested_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.requestsloan')),
            ],
        ),
    ]
