# Generated by Django 3.2.5 on 2021-07-17 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)])),
                ('loan_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.investor')),
                ('requested_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.requestsloan')),
            ],
            options={
                'unique_together': {('investor', 'requested_loan')},
                'index_together': {('investor', 'requested_loan')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'founded'), (1, 'completed')], default='founded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.offer')),
                ('requested_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.requestsloan')),
            ],
            options={
                'unique_together': {('requested_loan', 'accepted_offer')},
                'index_together': {('requested_loan', 'accepted_offer')},
            },
        ),
    ]
