# Generated by Django 3.2.5 on 2021-07-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'founded'), (1, 'completed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.requestsloan')),
            ],
        ),
    ]
