# Generated by Django 3.2.5 on 2021-07-16 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.offer'),
            preserve_default=False,
        ),
    ]
